### ISSUE TITLE
Feature Request: Add support for inline LaTeX

### ISSUE THREAD

**Issue by bys1123** [BenjaminHoegh/ParsedownExtended#10]
Writers usually explain LaTeX block in following section, 
this always need inline style LaTeX which in one dollar sign $ {LaTeX} $.

**Comment by BenjaminHoegh** [comment]
Thanks for the information. I will look at this a make a release with it soon :)

**Comment by BrainStone** [comment]
What's the status on this?

I would love to have that feature available.
Also looking at it, I think you missed to add `$` to the inline blocks.

**Comment by BenjaminHoegh** [comment]
The status is that this is made in the dev repo and is under bug testing so should be able to release it soon

**Comment by BenjaminHoegh** [comment]
Okay, so a status on the update. I'm should be ready to release it in this week, I do however been delayed as my PC broke down 2 times in a row (Happy me!) but it's now fixed and I'm back at coding

**Comment by BrainStone** [comment]
Sounds awesome. Looking forward to it
