### ISSUE TITLE
Table improvement

### ISSUE THREAD

**Issue by BenjaminHoegh** [BenjaminHoegh/ParsedownExtended#11]
https://github.com/erusev/parsedown/issues/682#issuecomment-466632520

**Comment by Lab-Things** [comment]
Hi, was this actually incorporated into ParsedownExtended? I'm using your extension, but the rowspan/colspan with ^ and > doesn't work. I'm trying to figure it if this is expected or if I'm doing something wrong

**Comment by BenjaminHoegh** [comment]
> Hi, was this actually incorporated into ParsedownExtended? I'm using your extension, but the rowspan/colspan with ^ and > doesn't work. I'm trying to figure it if this is expected or if I'm doing something wrong

No sorry, total forgot about this one

**Comment by KENNYSOFT** [comment]
https://github.com/BenjaminHoegh/ParsedownExtended/commit/17d9425ba6f9d59cfd0783269b24f37f64f872cc#diff-b805aead2f7de5ee5b7cb5be03ea7afe9a364079d92882433757d87ba4bb1679R1156-R1248

I think most of the implementation is based on [parsedown-tablespan](https://github.com/KENNYSOFT/parsedown-tablespan). Can you add some references?

**Comment by BenjaminHoegh** [comment]
> https://github.com/BenjaminHoegh/ParsedownExtended/commit/17d9425ba6f9d59cfd0783269b24f37f64f872cc#diff-b805aead2f7de5ee5b7cb5be03ea7afe9a364079d92882433757d87ba4bb1679R1156-R1248
> 
> 
> 
> I think most of the implementation is based on [ParsedownTablespan](https://github.com/KENNYSOFT/parsedown-tablespan). Can you add some references?

Sure, no problem :)
