### ISSUE TITLE
simplify syntax

### ISSUE THREAD

**Issue by glensc** [BenjaminHoegh/ParsedownExtended#12]
instead inventing new blocks, use the code fence language:

```
$$
    x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
$$
```

```
    ```math
        x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
    ```
```


```
%%
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts<br/>prevail...
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
%%
```


```
    ```mermaid
    sequenceDiagram
        participant Alice
        participant Bob
        Alice->>John: Hello John, how are you?
        loop Healthcheck
            John->>John: Fight against hypochondria
        end
        Note right of John: Rational thoughts<br/>prevail...
        John-->>Alice: Great!
        John->>Bob: How about you?
        Bob-->>John: Jolly good!
    ```
```

**Comment by BenjaminHoegh** [comment]
I do correctly working on change mermaid support to use the example you given. When it comes to LaTeX I will soon update it to use MatchJax standard
