### ISSUE TITLE
PHP message: PHP Notice:  Undefined index: text in .../parsedown_extra/ParsedownExtra.php on line 213

### ISSUE THREAD

**Issue by BrainStone** [BenjaminHoegh/ParsedownExtended#15]
Hi there.  
I'm trying to use the latest version of ParsedownExtended but it keeps throwing this error and just prints nothing:
```
PHP message: PHP Notice:  Undefined index: text in .../parsedown_extra/ParsedownExtra.php on line 213
```
(This messages spams over and over)

Using ParsedownExtra 0.8.1 and parsedown 1.8.0-beta-6.

**Comment by BenjaminHoegh** [comment]
This issue is related to the lasted version of ParsedownExtra 0.8.1 there doesn't work together with the Parsedown

You if you rollback to using ParsedownExtra 0.8.0 it should work

**Comment by BrainStone** [comment]
Is this an issue with Parsedown-Extra + Parsedown or ParsedownExtra + ParsedownExtendended?

**Comment by BenjaminHoegh** [comment]
between Parsedown-Extra and Parsedown
