### ISSUE TITLE
Add support for line

### ISSUE THREAD

**Issue by danbulant** [BenjaminHoegh/ParsedownExtended#19]
Using the `line` method to generate inline markdown doesn't use some (or any) features of parsedown extended (currently tried only using the `smartTypography` feature).

Works correctly with the `text` (block) method.

**Comment by BenjaminHoegh** [comment]
I have a fix ready for this but due to the poor internet connection, there are at where I'm staying in my holiday I can't upload it. I will make a release as soon as I get home
