### ISSUE TITLE
Hotfix Version v1.1.2 not available through Packagist

### ISSUE THREAD

**Issue by sweikenb** [BenjaminHoegh/ParsedownExtended#41]
### Describe the bug

The hotfix-release is not regsitered in [Packagist](https://packagist.org/packages/benjaminhoegh/parsedown-extended) which causes autoloading-errors.

### Expected Behavior

Verison 1.1.2 should be available through Packagist.

### Relevant log output

```shell
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires benjaminhoegh/parsedown-extended 1.1.2, found benjaminhoegh/parsedown-extended[dev-main, 0.1.1, ..., 0.1.6, 1.0-beta-4, ..., v1.1.1, 2.0.x-dev] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Environment

- PHP 8.1.8
- Composer version 2.3.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenjaminHoegh** [comment]
Thats weird it should update the packages automatically. Anyways I have updated it manually so it should be there now

**Comment by sweikenb** [comment]
Its working now, thank you very much for your quick response!
