### ISSUE TITLE
Extended parsing support for LaTeX

### ISSUE THREAD

**Issue by snorky22** [BenjaminHoegh/ParsedownExtended#42]
**Is your feature request related to a problem? Please describe.**
I appreciate the LaTeX support. It lets KaTeX or MathJax process inline equations, starting with `\(`and ending with `\)`. It would be nice to be able to display displaymath equations, i.e. code starting with `\[`and ending `\]`.

**Describe the solution you'd like**
When `math`is set to true, let the `\[` and `\]` be passed to the HTML code for the LaTeX interpreter to use them.

**Comment by BenjaminHoegh** [comment]
This should already be supported? what result do you get when using displaymath?

**Comment by snorky22** [comment]
The block math code I have is
```
  // Block Math
        $state = $this->options['math'] ?? false;
        if ($state !== false) {
            $this->BlockTypes['\\'][] = 'Math';
            $this->BlockTypes['$'][] = 'Math';
        }
```
It seems that it should use a double dollar `$$`. Do you think replacing `['$']`by `['$$']` would make the thing work for displaymath?

**Comment by snorky22** [comment]
I have made the previous modification and the math between `$$`and `$$`was not rendered.

**Comment by BenjaminHoegh** [comment]
The reason for `$this->BlockTypes['\\'][] = 'Math';` is do to how Parsedown works, in this case it should detect `\` and then activate the regular expression to see if the following are a match there should be formatted.

So for the sake of `$$` we use `$this->BlockTypes['$'][] = 'Math';` to find every `$` in our text, then running the regular expression, lets say `^\$\$`, from the position of the matched dollar sign, if it also match the expression we format it.


As for your issue, will it be possible for you to send a copy of the markdown that curse this issue?

**Comment by snorky22** [comment]
I have the following versions:
* Parsedown: version 1.8.0-beta-7
* ParsedownExtra: version 0.8.1
* ParsedownExtended: version 1.1

### Math enabled simple case
The creation code is
```	
	$Extra = new ParsedownExtended([
	"math" => true,
 	"toc" => true,
    "typographer" => true,
    "sup" => true,
    "sub" => true
	]);
```
The markdown is 
```
Let us display an differential equation in integral form:

\[x(t)=x_{0}+\int_{0}^{t}f(x(s))ds\]

Now let us put it into text by using the more compact differential form \(\frac{dx}{dt}=f(x)\;\;x(0)=x_{0}\). 
```
The HTML I get is
![simple Math](https://dsc.cloud/45a53a/CleanShot-2022-11-08-at-10.56.15-2x/CleanShot-2022-11-08-at-10.56.15-2x.png)

The inline math is rendered by MathJax, but the delimiters `\[` and `\]` are not passed to the final HTML.

### Math with dollars
The creation code is
```	
	$Extra = new ParsedownExtended([
	 "math" => [
        "single_dollar" => true
    ],
 	"toc" => true,
    "typographer" => true,
    "sup" => true,
    "sub" => true
	]);
```
The markdown is
```
Let us display an differential equation in integral form:

$$x(t)=x_{0}+\int_{0}^{t}f(x(s))ds$$

Now let us put it into text by using the more compact differential form $\frac{dx}{dt}=f(x)\;\;x(0)=x_{0}$. 
```
The HTML I get is
![Math with dollar delimiters](https://dsc.cloud/45a53a/CleanShot-2022-11-08-at-11.08.11-2x/CleanShot-2022-11-08-at-11.08.11-2x.png)

The double quotes should not be there.

Best regards,
François

**Comment by BenjaminHoegh** [comment]
Just a quick question, if you add a extra `\` before `\[` do it then work? If so it will be a issue with ParsedownExtended that I need to fix

**Comment by snorky22** [comment]
I have tried `\\[x(t)=x_{0}+\int_{0}^{t}f(x(s))ds\]`, `\\[x(t)=x_{0}+\int_{0}^{t}f(x(s))ds\\]` and `\\\[x(t)=x_{0}+\int_{0}^{t}f(x(s))ds\\\]`.
The first one returns `[x(t)=x{0}+\int{0}^{t}f(x(s))ds]`in the browser, the second one returns the same thing, and the last one returns `\[x(t)=x{0}+\int{0}^{t}f(x(s))ds\]`.
FYI, the HTML code returned from the standard code `\[x(t)=x_{0}+\int_{0}^{t}f(x(s))ds\]`(in markdown) is the HTML
```
<p>
"[x(t)=x"
<em>{0}+\int</em>
"{O}^{t}f(x(s))ds]"
</p>
```

**Comment by BenjaminHoegh** [comment]
Can confirm that in Parsedown 2.0 this is no longer a issue :)

I will see if I can back forward this to the current version

**Comment by BenjaminHoegh** [comment]
Sorry, didn't see your comment, yes you can use ParsedownExtra, the extension will automatic switch to use ParsedownExtra as base
