### ISSUE TITLE
Setter for $options

### ISSUE THREAD

**Issue by varrg** [BenjaminHoegh/ParsedownExtended#45]
Parsedown allows setting options through per-option setters (`setBreaksEnabled`, `setMarkupEscaped`, ...) which is handy when using the lib with `Parsedown::instance()->text($str)`

ParsedownExtended does not allow this, effectively forcing us to use `(new ParsedownExtended($options))->text($str))`

There should be a `setOptions()` method!

**Comment by BenjaminHoegh** [comment]
you thinking on having setters for each option or a separate function setOptions(array, $array)

what would you prefer ?

**Comment by varrg** [comment]
Maybe both, to keep in line with parsedown and offer the more convenient set with array method
