### ISSUE TITLE
mb_strtolower() function undefined?

### ISSUE THREAD

**Issue by sharpicx** [BenjaminHoegh/ParsedownExtended#62]
![image](https://github.com/BenjaminHoegh/ParsedownExtended/assets/44630640/40a0fab1-a635-4d87-8fdb-6ad40e34395f)

i cant even search where the `mb_strtolower()` will be called at. any solution?

**Comment by BenjaminHoegh** [comment]
I will strongly recommend you install the mbstring module, as this is very common and is huge improvement to the handling of non UTF-8 chars. 

I will release a version of the code with a fallback for users there doesn't have this module installed
